// Copyright 2025 ByteDance Inc. All rights reserved.
// Author: Yu WenTeng (yuwenteng@bytedance.com)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: products/understanding/base/au_base.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_ERROR_UNSPECIFIED Code = 0
	Code_SUCCESS           Code = 21000
	// request related
	Code_INVALID_REQUEST   Code = 11100
	Code_PERMISSION_DENIED Code = 11200
	Code_LIMIT_QPS         Code = 11301
	Code_LIMIT_COUNT       Code = 11302
	Code_SERVER_BUSY       Code = 11303
	Code_INTERRUPTED       Code = 21300
	Code_ERROR_PARAMS      Code = 11500
	// audio related
	Code_LONG_AUDIO          Code = 11101
	Code_LARGE_PACKET        Code = 11102
	Code_INVALID_FORMAT      Code = 11103
	Code_SILENT_AUDIO        Code = 11104
	Code_EMPTY_AUDIO         Code = 11105
	Code_AUDIO_DOWNLOAD_FAIL Code = 21701
	// recognition related
	Code_TIMEOUT_WAITING    Code = 21200
	Code_TIMEOUT_PROCESSING Code = 21201
	Code_ERROR_PROCESSING   Code = 21100
	// others
	Code_ERROR_UNKNOWN Code = 29900
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:     "ERROR_UNSPECIFIED",
		21000: "SUCCESS",
		11100: "INVALID_REQUEST",
		11200: "PERMISSION_DENIED",
		11301: "LIMIT_QPS",
		11302: "LIMIT_COUNT",
		11303: "SERVER_BUSY",
		21300: "INTERRUPTED",
		11500: "ERROR_PARAMS",
		11101: "LONG_AUDIO",
		11102: "LARGE_PACKET",
		11103: "INVALID_FORMAT",
		11104: "SILENT_AUDIO",
		11105: "EMPTY_AUDIO",
		21701: "AUDIO_DOWNLOAD_FAIL",
		21200: "TIMEOUT_WAITING",
		21201: "TIMEOUT_PROCESSING",
		21100: "ERROR_PROCESSING",
		29900: "ERROR_UNKNOWN",
	}
	Code_value = map[string]int32{
		"ERROR_UNSPECIFIED":   0,
		"SUCCESS":             21000,
		"INVALID_REQUEST":     11100,
		"PERMISSION_DENIED":   11200,
		"LIMIT_QPS":           11301,
		"LIMIT_COUNT":         11302,
		"SERVER_BUSY":         11303,
		"INTERRUPTED":         21300,
		"ERROR_PARAMS":        11500,
		"LONG_AUDIO":          11101,
		"LARGE_PACKET":        11102,
		"INVALID_FORMAT":      11103,
		"SILENT_AUDIO":        11104,
		"EMPTY_AUDIO":         11105,
		"AUDIO_DOWNLOAD_FAIL": 21701,
		"TIMEOUT_WAITING":     21200,
		"TIMEOUT_PROCESSING":  21201,
		"ERROR_PROCESSING":    21100,
		"ERROR_UNKNOWN":       29900,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_products_understanding_base_au_base_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_products_understanding_base_au_base_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{0}
}

type AsrNotificationCode int32

const (
	AsrNotificationCode_NOTIFICATION_UNSPECIFIED AsrNotificationCode = 0
	AsrNotificationCode_DISCONNECT               AsrNotificationCode = 1000
)

// Enum value maps for AsrNotificationCode.
var (
	AsrNotificationCode_name = map[int32]string{
		0:    "NOTIFICATION_UNSPECIFIED",
		1000: "DISCONNECT",
	}
	AsrNotificationCode_value = map[string]int32{
		"NOTIFICATION_UNSPECIFIED": 0,
		"DISCONNECT":               1000,
	}
)

func (x AsrNotificationCode) Enum() *AsrNotificationCode {
	p := new(AsrNotificationCode)
	*p = x
	return p
}

func (x AsrNotificationCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AsrNotificationCode) Descriptor() protoreflect.EnumDescriptor {
	return file_products_understanding_base_au_base_proto_enumTypes[1].Descriptor()
}

func (AsrNotificationCode) Type() protoreflect.EnumType {
	return &file_products_understanding_base_au_base_proto_enumTypes[1]
}

func (x AsrNotificationCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AsrNotificationCode.Descriptor instead.
func (AsrNotificationCode) EnumDescriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{1}
}

type Word struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	StartTime     int32                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int32                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	BlankDuration int32                  `protobuf:"varint,4,opt,name=blank_duration,json=blankDuration,proto3" json:"blank_duration,omitempty"`
	Pronounce     string                 `protobuf:"bytes,5,opt,name=pronounce,proto3" json:"pronounce,omitempty"`
	Confidence    float64                `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Word) Reset() {
	*x = Word{}
	mi := &file_products_understanding_base_au_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_base_au_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{0}
}

func (x *Word) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Word) GetStartTime() int32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Word) GetEndTime() int32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Word) GetBlankDuration() int32 {
	if x != nil {
		return x.BlankDuration
	}
	return 0
}

func (x *Word) GetPronounce() string {
	if x != nil {
		return x.Pronounce
	}
	return ""
}

func (x *Word) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type UtteranceAddition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtteranceAddition) Reset() {
	*x = UtteranceAddition{}
	mi := &file_products_understanding_base_au_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtteranceAddition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtteranceAddition) ProtoMessage() {}

func (x *UtteranceAddition) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_base_au_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtteranceAddition.ProtoReflect.Descriptor instead.
func (*UtteranceAddition) Descriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{1}
}

type ResultAddition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultAddition) Reset() {
	*x = ResultAddition{}
	mi := &file_products_understanding_base_au_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultAddition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultAddition) ProtoMessage() {}

func (x *ResultAddition) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_base_au_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultAddition.ProtoReflect.Descriptor instead.
func (*ResultAddition) Descriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{2}
}

type Utterance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	StartTime     int32                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int32                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Definite      *bool                  `protobuf:"varint,4,opt,name=definite,proto3,oneof" json:"definite,omitempty"`
	Words         []*Word                `protobuf:"bytes,5,rep,name=words,proto3" json:"words,omitempty"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Confidence    float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Speaker       int32                  `protobuf:"varint,8,opt,name=speaker,proto3" json:"speaker,omitempty"`
	ChannelId     int32                  `protobuf:"varint,9,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Additions     map[string]string      `protobuf:"bytes,100,rep,name=additions,proto3" json:"additions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Utterance) Reset() {
	*x = Utterance{}
	mi := &file_products_understanding_base_au_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Utterance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Utterance) ProtoMessage() {}

func (x *Utterance) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_base_au_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Utterance.ProtoReflect.Descriptor instead.
func (*Utterance) Descriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{3}
}

func (x *Utterance) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Utterance) GetStartTime() int32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Utterance) GetEndTime() int32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Utterance) GetDefinite() bool {
	if x != nil && x.Definite != nil {
		return *x.Definite
	}
	return false
}

func (x *Utterance) GetWords() []*Word {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *Utterance) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Utterance) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Utterance) GetSpeaker() int32 {
	if x != nil {
		return x.Speaker
	}
	return 0
}

func (x *Utterance) GetChannelId() int32 {
	if x != nil {
		return x.ChannelId
	}
	return 0
}

func (x *Utterance) GetAdditions() map[string]string {
	if x != nil {
		return x.Additions
	}
	return nil
}

type LanguageDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// language probability
	Prob          float64 `protobuf:"fixed64,1,opt,name=prob,proto3" json:"prob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LanguageDetail) Reset() {
	*x = LanguageDetail{}
	mi := &file_products_understanding_base_au_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LanguageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LanguageDetail) ProtoMessage() {}

func (x *LanguageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_base_au_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LanguageDetail.ProtoReflect.Descriptor instead.
func (*LanguageDetail) Descriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{4}
}

func (x *LanguageDetail) GetProb() float64 {
	if x != nil {
		return x.Prob
	}
	return 0
}

type Result struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	Text             string                     `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Utterances       []*Utterance               `protobuf:"bytes,2,rep,name=utterances,proto3" json:"utterances,omitempty"`
	Confidence       float64                    `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	GlobalConfidence float64                    `protobuf:"fixed64,4,opt,name=global_confidence,json=globalConfidence,proto3" json:"global_confidence,omitempty"`
	Language         string                     `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	LanguageDetails  map[string]*LanguageDetail `protobuf:"bytes,6,rep,name=language_details,json=languageDetails,proto3" json:"language_details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Termination      *bool                      `protobuf:"varint,7,opt,name=termination,proto3,oneof" json:"termination,omitempty"`
	Volume           float64                    `protobuf:"fixed64,8,opt,name=volume,proto3" json:"volume,omitempty"`
	SpeechRate       float64                    `protobuf:"fixed64,9,opt,name=speech_rate,json=speechRate,proto3" json:"speech_rate,omitempty"`
	ResultType       string                     `protobuf:"bytes,10,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"`
	OriText          string                     `protobuf:"bytes,11,opt,name=ori_text,json=oriText,proto3" json:"ori_text,omitempty"`
	Prefetch         *bool                      `protobuf:"varint,12,opt,name=prefetch,proto3,oneof" json:"prefetch,omitempty"`
	Additions        map[string]string          `protobuf:"bytes,100,rep,name=additions,proto3" json:"additions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_products_understanding_base_au_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_base_au_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{5}
}

func (x *Result) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Result) GetUtterances() []*Utterance {
	if x != nil {
		return x.Utterances
	}
	return nil
}

func (x *Result) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Result) GetGlobalConfidence() float64 {
	if x != nil {
		return x.GlobalConfidence
	}
	return 0
}

func (x *Result) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Result) GetLanguageDetails() map[string]*LanguageDetail {
	if x != nil {
		return x.LanguageDetails
	}
	return nil
}

func (x *Result) GetTermination() bool {
	if x != nil && x.Termination != nil {
		return *x.Termination
	}
	return false
}

func (x *Result) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Result) GetSpeechRate() float64 {
	if x != nil {
		return x.SpeechRate
	}
	return 0
}

func (x *Result) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *Result) GetOriText() string {
	if x != nil {
		return x.OriText
	}
	return ""
}

func (x *Result) GetPrefetch() bool {
	if x != nil && x.Prefetch != nil {
		return *x.Prefetch
	}
	return false
}

func (x *Result) GetAdditions() map[string]string {
	if x != nil {
		return x.Additions
	}
	return nil
}

type AudioInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      int64                  `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	SpeechRate    float64                `protobuf:"fixed64,2,opt,name=speech_rate,json=speechRate,proto3" json:"speech_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioInfo) Reset() {
	*x = AudioInfo{}
	mi := &file_products_understanding_base_au_base_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioInfo) ProtoMessage() {}

func (x *AudioInfo) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_base_au_base_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioInfo.ProtoReflect.Descriptor instead.
func (*AudioInfo) Descriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{6}
}

func (x *AudioInfo) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AudioInfo) GetSpeechRate() float64 {
	if x != nil {
		return x.SpeechRate
	}
	return 0
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkFlowName  string                 `protobuf:"bytes,1,opt,name=work_flow_name,json=workFlowName,proto3" json:"work_flow_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_products_understanding_base_au_base_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_base_au_base_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{7}
}

func (x *App) GetWorkFlowName() string {
	if x != nil {
		return x.WorkFlowName
	}
	return ""
}

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Uid   string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Did   string                 `protobuf:"bytes,2,opt,name=did,proto3" json:"did,omitempty"`
	// android or ios info
	Platform      string `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	SdkVersion    string `protobuf:"bytes,4,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	AppVersion    string `protobuf:"bytes,5,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_products_understanding_base_au_base_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_base_au_base_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{8}
}

func (x *User) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *User) GetDid() string {
	if x != nil {
		return x.Did
	}
	return ""
}

func (x *User) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *User) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *User) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

type Audio struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Url   string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// url; vid...
	UrlType        string `protobuf:"bytes,3,opt,name=url_type,json=urlType,proto3" json:"url_type,omitempty"`
	Format         string `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Codec          string `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"`
	Language       string `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	Rate           int32  `protobuf:"varint,7,opt,name=rate,proto3" json:"rate,omitempty"`
	Bits           int32  `protobuf:"varint,8,opt,name=bits,proto3" json:"bits,omitempty"`
	Channel        int32  `protobuf:"varint,9,opt,name=channel,proto3" json:"channel,omitempty"`
	TosBucket      string `protobuf:"bytes,10,opt,name=tos_bucket,json=tosBucket,proto3" json:"tos_bucket,omitempty"`
	TosAccessKey   string `protobuf:"bytes,11,opt,name=tos_access_key,json=tosAccessKey,proto3" json:"tos_access_key,omitempty"`
	AudioTosObject string `protobuf:"bytes,12,opt,name=audio_tos_object,json=audioTosObject,proto3" json:"audio_tos_object,omitempty"`
	RoleTrn        string `protobuf:"bytes,13,opt,name=role_trn,json=roleTrn,proto3" json:"role_trn,omitempty"`
	BinaryData     []byte `protobuf:"bytes,14,opt,name=binary_data,json=binaryData,proto3" json:"binary_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Audio) Reset() {
	*x = Audio{}
	mi := &file_products_understanding_base_au_base_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audio) ProtoMessage() {}

func (x *Audio) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_base_au_base_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audio.ProtoReflect.Descriptor instead.
func (*Audio) Descriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{9}
}

func (x *Audio) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Audio) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Audio) GetUrlType() string {
	if x != nil {
		return x.UrlType
	}
	return ""
}

func (x *Audio) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Audio) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *Audio) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Audio) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *Audio) GetBits() int32 {
	if x != nil {
		return x.Bits
	}
	return 0
}

func (x *Audio) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *Audio) GetTosBucket() string {
	if x != nil {
		return x.TosBucket
	}
	return ""
}

func (x *Audio) GetTosAccessKey() string {
	if x != nil {
		return x.TosAccessKey
	}
	return ""
}

func (x *Audio) GetAudioTosObject() string {
	if x != nil {
		return x.AudioTosObject
	}
	return ""
}

func (x *Audio) GetRoleTrn() string {
	if x != nil {
		return x.RoleTrn
	}
	return ""
}

func (x *Audio) GetBinaryData() []byte {
	if x != nil {
		return x.BinaryData
	}
	return nil
}

type AsrNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          AsrNotificationCode    `protobuf:"varint,1,opt,name=code,proto3,enum=data.speech.understanding.AsrNotificationCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsrNotification) Reset() {
	*x = AsrNotification{}
	mi := &file_products_understanding_base_au_base_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsrNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsrNotification) ProtoMessage() {}

func (x *AsrNotification) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_base_au_base_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsrNotification.ProtoReflect.Descriptor instead.
func (*AsrNotification) Descriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{10}
}

func (x *AsrNotification) GetCode() AsrNotificationCode {
	if x != nil {
		return x.Code
	}
	return AsrNotificationCode_NOTIFICATION_UNSPECIFIED
}

func (x *AsrNotification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReqParams struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ModelName            string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`    // 用于映射集群
	ConfigName           string                 `protobuf:"bytes,2,opt,name=config_name,json=configName,proto3" json:"config_name,omitempty"` // 用于映射tcc配置
	EnableVad            *bool                  `protobuf:"varint,3,opt,name=enable_vad,json=enableVad,proto3,oneof" json:"enable_vad,omitempty"`
	EnablePunc           *bool                  `protobuf:"varint,4,opt,name=enable_punc,json=enablePunc,proto3,oneof" json:"enable_punc,omitempty"`
	EnableItn            *bool                  `protobuf:"varint,5,opt,name=enable_itn,json=enableItn,proto3,oneof" json:"enable_itn,omitempty"`
	EnableDdc            *bool                  `protobuf:"varint,6,opt,name=enable_ddc,json=enableDdc,proto3,oneof" json:"enable_ddc,omitempty"`
	EnableResample       *bool                  `protobuf:"varint,7,opt,name=enable_resample,json=enableResample,proto3,oneof" json:"enable_resample,omitempty"`
	VadSignal            *bool                  `protobuf:"varint,8,opt,name=vad_signal,json=vadSignal,proto3,oneof" json:"vad_signal,omitempty"`
	EnableTranslate      *bool                  `protobuf:"varint,9,opt,name=enable_translate,json=enableTranslate,proto3,oneof" json:"enable_translate,omitempty"`
	DisableEndPunc       *bool                  `protobuf:"varint,10,opt,name=disable_end_punc,json=disableEndPunc,proto3,oneof" json:"disable_end_punc,omitempty"`
	EnableSpeakerInfo    *bool                  `protobuf:"varint,11,opt,name=enable_speaker_info,json=enableSpeakerInfo,proto3,oneof" json:"enable_speaker_info,omitempty"`
	EnableChannelSplit   *bool                  `protobuf:"varint,12,opt,name=enable_channel_split,json=enableChannelSplit,proto3,oneof" json:"enable_channel_split,omitempty"`
	AppLang              string                 `protobuf:"bytes,13,opt,name=app_lang,json=appLang,proto3" json:"app_lang,omitempty"`
	Country              string                 `protobuf:"bytes,14,opt,name=country,proto3" json:"country,omitempty"`
	AudioType            string                 `protobuf:"bytes,15,opt,name=audio_type,json=audioType,proto3" json:"audio_type,omitempty"`
	EnableLid            *bool                  `protobuf:"varint,16,opt,name=enable_lid,json=enableLid,proto3,oneof" json:"enable_lid,omitempty"`
	Reco2ActNumSpk       int32                  `protobuf:"varint,17,opt,name=reco2act_num_spk,json=reco2actNumSpk,proto3" json:"reco2act_num_spk,omitempty"`
	Reco2MaxNumSpk       int32                  `protobuf:"varint,18,opt,name=reco2max_num_spk,json=reco2maxNumSpk,proto3" json:"reco2max_num_spk,omitempty"`
	EnableInterrupt      *bool                  `protobuf:"varint,19,opt,name=enable_interrupt,json=enableInterrupt,proto3,oneof" json:"enable_interrupt,omitempty"`
	VadSegment           *bool                  `protobuf:"varint,20,opt,name=vad_segment,json=vadSegment,proto3,oneof" json:"vad_segment,omitempty"`
	EnableOriText        *bool                  `protobuf:"varint,21,opt,name=enable_ori_text,json=enableOriText,proto3,oneof" json:"enable_ori_text,omitempty"`
	EnableNonstream      *bool                  `protobuf:"varint,22,opt,name=enable_nonstream,json=enableNonstream,proto3,oneof" json:"enable_nonstream,omitempty"`
	ShowUtterances       *bool                  `protobuf:"varint,31,opt,name=show_utterances,json=showUtterances,proto3,oneof" json:"show_utterances,omitempty"`
	ShowWords            *bool                  `protobuf:"varint,32,opt,name=show_words,json=showWords,proto3,oneof" json:"show_words,omitempty"`
	ShowDuration         *bool                  `protobuf:"varint,33,opt,name=show_duration,json=showDuration,proto3,oneof" json:"show_duration,omitempty"`
	ShowLanguage         *bool                  `protobuf:"varint,34,opt,name=show_language,json=showLanguage,proto3,oneof" json:"show_language,omitempty"`
	ShowVolume           *bool                  `protobuf:"varint,35,opt,name=show_volume,json=showVolume,proto3,oneof" json:"show_volume,omitempty"`
	ShowVolumeV          *bool                  `protobuf:"varint,362,opt,name=show_volume_v,json=showVolumeV,proto3,oneof" json:"show_volume_v,omitempty"`
	ShowSpeechRate       *bool                  `protobuf:"varint,37,opt,name=show_speech_rate,json=showSpeechRate,proto3,oneof" json:"show_speech_rate,omitempty"`
	ShowPrefetch         *bool                  `protobuf:"varint,38,opt,name=show_prefetch,json=showPrefetch,proto3,oneof" json:"show_prefetch,omitempty"`
	ResultType           string                 `protobuf:"bytes,39,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"`
	StartSilenceTime     int32                  `protobuf:"varint,61,opt,name=start_silence_time,json=startSilenceTime,proto3" json:"start_silence_time,omitempty"`
	EndSilenceTime       int32                  `protobuf:"varint,62,opt,name=end_silence_time,json=endSilenceTime,proto3" json:"end_silence_time,omitempty"`
	VadSilenceTime       int32                  `protobuf:"varint,63,opt,name=vad_silence_time,json=vadSilenceTime,proto3" json:"vad_silence_time,omitempty"`
	MinSilenceTime       int32                  `protobuf:"varint,64,opt,name=min_silence_time,json=minSilenceTime,proto3" json:"min_silence_time,omitempty"`
	VadMode              string                 `protobuf:"bytes,65,opt,name=vad_mode,json=vadMode,proto3" json:"vad_mode,omitempty"`
	VadSegmentDuration   int32                  `protobuf:"varint,66,opt,name=vad_segment_duration,json=vadSegmentDuration,proto3" json:"vad_segment_duration,omitempty"`
	EndWindowSize        int32                  `protobuf:"varint,67,opt,name=end_window_size,json=endWindowSize,proto3" json:"end_window_size,omitempty"`
	ForceToSpeechTime    int32                  `protobuf:"varint,68,opt,name=force_to_speech_time,json=forceToSpeechTime,proto3" json:"force_to_speech_time,omitempty"`
	Corpus               *Corpus                `protobuf:"bytes,100,opt,name=corpus,proto3" json:"corpus,omitempty"`
	Notification         *AsrNotification       `protobuf:"bytes,101,opt,name=notification,proto3" json:"notification,omitempty"`
	SensitiveWordsFilter string                 `protobuf:"bytes,102,opt,name=sensitive_words_filter,json=sensitiveWordsFilter,proto3" json:"sensitive_words_filter,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ReqParams) Reset() {
	*x = ReqParams{}
	mi := &file_products_understanding_base_au_base_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqParams) ProtoMessage() {}

func (x *ReqParams) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_base_au_base_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqParams.ProtoReflect.Descriptor instead.
func (*ReqParams) Descriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{11}
}

func (x *ReqParams) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ReqParams) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *ReqParams) GetEnableVad() bool {
	if x != nil && x.EnableVad != nil {
		return *x.EnableVad
	}
	return false
}

func (x *ReqParams) GetEnablePunc() bool {
	if x != nil && x.EnablePunc != nil {
		return *x.EnablePunc
	}
	return false
}

func (x *ReqParams) GetEnableItn() bool {
	if x != nil && x.EnableItn != nil {
		return *x.EnableItn
	}
	return false
}

func (x *ReqParams) GetEnableDdc() bool {
	if x != nil && x.EnableDdc != nil {
		return *x.EnableDdc
	}
	return false
}

func (x *ReqParams) GetEnableResample() bool {
	if x != nil && x.EnableResample != nil {
		return *x.EnableResample
	}
	return false
}

func (x *ReqParams) GetVadSignal() bool {
	if x != nil && x.VadSignal != nil {
		return *x.VadSignal
	}
	return false
}

func (x *ReqParams) GetEnableTranslate() bool {
	if x != nil && x.EnableTranslate != nil {
		return *x.EnableTranslate
	}
	return false
}

func (x *ReqParams) GetDisableEndPunc() bool {
	if x != nil && x.DisableEndPunc != nil {
		return *x.DisableEndPunc
	}
	return false
}

func (x *ReqParams) GetEnableSpeakerInfo() bool {
	if x != nil && x.EnableSpeakerInfo != nil {
		return *x.EnableSpeakerInfo
	}
	return false
}

func (x *ReqParams) GetEnableChannelSplit() bool {
	if x != nil && x.EnableChannelSplit != nil {
		return *x.EnableChannelSplit
	}
	return false
}

func (x *ReqParams) GetAppLang() string {
	if x != nil {
		return x.AppLang
	}
	return ""
}

func (x *ReqParams) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ReqParams) GetAudioType() string {
	if x != nil {
		return x.AudioType
	}
	return ""
}

func (x *ReqParams) GetEnableLid() bool {
	if x != nil && x.EnableLid != nil {
		return *x.EnableLid
	}
	return false
}

func (x *ReqParams) GetReco2ActNumSpk() int32 {
	if x != nil {
		return x.Reco2ActNumSpk
	}
	return 0
}

func (x *ReqParams) GetReco2MaxNumSpk() int32 {
	if x != nil {
		return x.Reco2MaxNumSpk
	}
	return 0
}

func (x *ReqParams) GetEnableInterrupt() bool {
	if x != nil && x.EnableInterrupt != nil {
		return *x.EnableInterrupt
	}
	return false
}

func (x *ReqParams) GetVadSegment() bool {
	if x != nil && x.VadSegment != nil {
		return *x.VadSegment
	}
	return false
}

func (x *ReqParams) GetEnableOriText() bool {
	if x != nil && x.EnableOriText != nil {
		return *x.EnableOriText
	}
	return false
}

func (x *ReqParams) GetEnableNonstream() bool {
	if x != nil && x.EnableNonstream != nil {
		return *x.EnableNonstream
	}
	return false
}

func (x *ReqParams) GetShowUtterances() bool {
	if x != nil && x.ShowUtterances != nil {
		return *x.ShowUtterances
	}
	return false
}

func (x *ReqParams) GetShowWords() bool {
	if x != nil && x.ShowWords != nil {
		return *x.ShowWords
	}
	return false
}

func (x *ReqParams) GetShowDuration() bool {
	if x != nil && x.ShowDuration != nil {
		return *x.ShowDuration
	}
	return false
}

func (x *ReqParams) GetShowLanguage() bool {
	if x != nil && x.ShowLanguage != nil {
		return *x.ShowLanguage
	}
	return false
}

func (x *ReqParams) GetShowVolume() bool {
	if x != nil && x.ShowVolume != nil {
		return *x.ShowVolume
	}
	return false
}

func (x *ReqParams) GetShowVolumeV() bool {
	if x != nil && x.ShowVolumeV != nil {
		return *x.ShowVolumeV
	}
	return false
}

func (x *ReqParams) GetShowSpeechRate() bool {
	if x != nil && x.ShowSpeechRate != nil {
		return *x.ShowSpeechRate
	}
	return false
}

func (x *ReqParams) GetShowPrefetch() bool {
	if x != nil && x.ShowPrefetch != nil {
		return *x.ShowPrefetch
	}
	return false
}

func (x *ReqParams) GetResultType() string {
	if x != nil {
		return x.ResultType
	}
	return ""
}

func (x *ReqParams) GetStartSilenceTime() int32 {
	if x != nil {
		return x.StartSilenceTime
	}
	return 0
}

func (x *ReqParams) GetEndSilenceTime() int32 {
	if x != nil {
		return x.EndSilenceTime
	}
	return 0
}

func (x *ReqParams) GetVadSilenceTime() int32 {
	if x != nil {
		return x.VadSilenceTime
	}
	return 0
}

func (x *ReqParams) GetMinSilenceTime() int32 {
	if x != nil {
		return x.MinSilenceTime
	}
	return 0
}

func (x *ReqParams) GetVadMode() string {
	if x != nil {
		return x.VadMode
	}
	return ""
}

func (x *ReqParams) GetVadSegmentDuration() int32 {
	if x != nil {
		return x.VadSegmentDuration
	}
	return 0
}

func (x *ReqParams) GetEndWindowSize() int32 {
	if x != nil {
		return x.EndWindowSize
	}
	return 0
}

func (x *ReqParams) GetForceToSpeechTime() int32 {
	if x != nil {
		return x.ForceToSpeechTime
	}
	return 0
}

func (x *ReqParams) GetCorpus() *Corpus {
	if x != nil {
		return x.Corpus
	}
	return nil
}

func (x *ReqParams) GetNotification() *AsrNotification {
	if x != nil {
		return x.Notification
	}
	return nil
}

func (x *ReqParams) GetSensitiveWordsFilter() string {
	if x != nil {
		return x.SensitiveWordsFilter
	}
	return ""
}

type Corpus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// json格式，包含热词，冷词，篇章，纠错词表等
	Context               string            `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	BoostingTableId       string            `protobuf:"bytes,2,opt,name=boosting_table_id,json=boostingTableId,proto3" json:"boosting_table_id,omitempty"`
	BoostingTableName     string            `protobuf:"bytes,3,opt,name=boosting_table_name,json=boostingTableName,proto3" json:"boosting_table_name,omitempty"`
	BoostingId            string            `protobuf:"bytes,4,opt,name=boosting_id,json=boostingId,proto3" json:"boosting_id,omitempty"`
	NnlmId                string            `protobuf:"bytes,5,opt,name=nnlm_id,json=nnlmId,proto3" json:"nnlm_id,omitempty"`
	CorrectTableId        string            `protobuf:"bytes,6,opt,name=correct_table_id,json=correctTableId,proto3" json:"correct_table_id,omitempty"`
	CorrectTableName      string            `protobuf:"bytes,7,opt,name=correct_table_name,json=correctTableName,proto3" json:"correct_table_name,omitempty"`
	PuncHotWords          string            `protobuf:"bytes,8,opt,name=punc_hot_words,json=puncHotWords,proto3" json:"punc_hot_words,omitempty"`
	HotWordsList          []string          `protobuf:"bytes,9,rep,name=hot_words_list,json=hotWordsList,proto3" json:"hot_words_list,omitempty"`
	GlossaryList          map[string]string `protobuf:"bytes,10,rep,name=glossary_list,json=glossaryList,proto3" json:"glossary_list,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CorrectWords          string            `protobuf:"bytes,11,opt,name=correct_words,json=correctWords,proto3" json:"correct_words,omitempty"`
	RegexCorrectTableId   string            `protobuf:"bytes,12,opt,name=regex_correct_table_id,json=regexCorrectTableId,proto3" json:"regex_correct_table_id,omitempty"`
	RegexCorrectTableName string            `protobuf:"bytes,13,opt,name=regex_correct_table_name,json=regexCorrectTableName,proto3" json:"regex_correct_table_name,omitempty"`
	GlossaryTableId       string            `protobuf:"bytes,14,opt,name=glossary_table_id,json=glossaryTableId,proto3" json:"glossary_table_id,omitempty"`
	GlossaryTableName     string            `protobuf:"bytes,15,opt,name=glossary_table_name,json=glossaryTableName,proto3" json:"glossary_table_name,omitempty"`
	ShowMatchHotWords     *bool             `protobuf:"varint,61,opt,name=show_match_hot_words,json=showMatchHotWords,proto3,oneof" json:"show_match_hot_words,omitempty"`
	ShowAllMatchHotWords  *bool             `protobuf:"varint,62,opt,name=show_all_match_hot_words,json=showAllMatchHotWords,proto3,oneof" json:"show_all_match_hot_words,omitempty"`
	ShowEffectiveHotWords *bool             `protobuf:"varint,63,opt,name=show_effective_hot_words,json=showEffectiveHotWords,proto3,oneof" json:"show_effective_hot_words,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Corpus) Reset() {
	*x = Corpus{}
	mi := &file_products_understanding_base_au_base_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Corpus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Corpus) ProtoMessage() {}

func (x *Corpus) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_base_au_base_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Corpus.ProtoReflect.Descriptor instead.
func (*Corpus) Descriptor() ([]byte, []int) {
	return file_products_understanding_base_au_base_proto_rawDescGZIP(), []int{12}
}

func (x *Corpus) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *Corpus) GetBoostingTableId() string {
	if x != nil {
		return x.BoostingTableId
	}
	return ""
}

func (x *Corpus) GetBoostingTableName() string {
	if x != nil {
		return x.BoostingTableName
	}
	return ""
}

func (x *Corpus) GetBoostingId() string {
	if x != nil {
		return x.BoostingId
	}
	return ""
}

func (x *Corpus) GetNnlmId() string {
	if x != nil {
		return x.NnlmId
	}
	return ""
}

func (x *Corpus) GetCorrectTableId() string {
	if x != nil {
		return x.CorrectTableId
	}
	return ""
}

func (x *Corpus) GetCorrectTableName() string {
	if x != nil {
		return x.CorrectTableName
	}
	return ""
}

func (x *Corpus) GetPuncHotWords() string {
	if x != nil {
		return x.PuncHotWords
	}
	return ""
}

func (x *Corpus) GetHotWordsList() []string {
	if x != nil {
		return x.HotWordsList
	}
	return nil
}

func (x *Corpus) GetGlossaryList() map[string]string {
	if x != nil {
		return x.GlossaryList
	}
	return nil
}

func (x *Corpus) GetCorrectWords() string {
	if x != nil {
		return x.CorrectWords
	}
	return ""
}

func (x *Corpus) GetRegexCorrectTableId() string {
	if x != nil {
		return x.RegexCorrectTableId
	}
	return ""
}

func (x *Corpus) GetRegexCorrectTableName() string {
	if x != nil {
		return x.RegexCorrectTableName
	}
	return ""
}

func (x *Corpus) GetGlossaryTableId() string {
	if x != nil {
		return x.GlossaryTableId
	}
	return ""
}

func (x *Corpus) GetGlossaryTableName() string {
	if x != nil {
		return x.GlossaryTableName
	}
	return ""
}

func (x *Corpus) GetShowMatchHotWords() bool {
	if x != nil && x.ShowMatchHotWords != nil {
		return *x.ShowMatchHotWords
	}
	return false
}

func (x *Corpus) GetShowAllMatchHotWords() bool {
	if x != nil && x.ShowAllMatchHotWords != nil {
		return *x.ShowAllMatchHotWords
	}
	return false
}

func (x *Corpus) GetShowEffectiveHotWords() bool {
	if x != nil && x.ShowEffectiveHotWords != nil {
		return *x.ShowEffectiveHotWords
	}
	return false
}

var File_products_understanding_base_au_base_proto protoreflect.FileDescriptor

const file_products_understanding_base_au_base_proto_rawDesc = "" +
	"\n" +
	")products/understanding/base/au_base.proto\x12\x19data.speech.understanding\"\xb9\x01\n" +
	"\x04Word\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x05R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x05R\aendTime\x12%\n" +
	"\x0eblank_duration\x18\x04 \x01(\x05R\rblankDuration\x12\x1c\n" +
	"\tpronounce\x18\x05 \x01(\tR\tpronounce\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\"\x13\n" +
	"\x11UtteranceAddition\"\x10\n" +
	"\x0eResultAddition\"\xc4\x03\n" +
	"\tUtterance\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x05R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x05R\aendTime\x12\x1f\n" +
	"\bdefinite\x18\x04 \x01(\bH\x00R\bdefinite\x88\x01\x01\x125\n" +
	"\x05words\x18\x05 \x03(\v2\x1f.data.speech.understanding.WordR\x05words\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x12\x18\n" +
	"\aspeaker\x18\b \x01(\x05R\aspeaker\x12\x1d\n" +
	"\n" +
	"channel_id\x18\t \x01(\x05R\tchannelId\x12Q\n" +
	"\tadditions\x18d \x03(\v23.data.speech.understanding.Utterance.AdditionsEntryR\tadditions\x1a<\n" +
	"\x0eAdditionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\v\n" +
	"\t_definite\"$\n" +
	"\x0eLanguageDetail\x12\x12\n" +
	"\x04prob\x18\x01 \x01(\x01R\x04prob\"\x85\x06\n" +
	"\x06Result\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12D\n" +
	"\n" +
	"utterances\x18\x02 \x03(\v2$.data.speech.understanding.UtteranceR\n" +
	"utterances\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12+\n" +
	"\x11global_confidence\x18\x04 \x01(\x01R\x10globalConfidence\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\x12a\n" +
	"\x10language_details\x18\x06 \x03(\v26.data.speech.understanding.Result.LanguageDetailsEntryR\x0flanguageDetails\x12%\n" +
	"\vtermination\x18\a \x01(\bH\x00R\vtermination\x88\x01\x01\x12\x16\n" +
	"\x06volume\x18\b \x01(\x01R\x06volume\x12\x1f\n" +
	"\vspeech_rate\x18\t \x01(\x01R\n" +
	"speechRate\x12\x1f\n" +
	"\vresult_type\x18\n" +
	" \x01(\tR\n" +
	"resultType\x12\x19\n" +
	"\bori_text\x18\v \x01(\tR\aoriText\x12\x1f\n" +
	"\bprefetch\x18\f \x01(\bH\x01R\bprefetch\x88\x01\x01\x12N\n" +
	"\tadditions\x18d \x03(\v20.data.speech.understanding.Result.AdditionsEntryR\tadditions\x1am\n" +
	"\x14LanguageDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12?\n" +
	"\x05value\x18\x02 \x01(\v2).data.speech.understanding.LanguageDetailR\x05value:\x028\x01\x1a<\n" +
	"\x0eAdditionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_terminationB\v\n" +
	"\t_prefetch\"H\n" +
	"\tAudioInfo\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\x03R\bduration\x12\x1f\n" +
	"\vspeech_rate\x18\x02 \x01(\x01R\n" +
	"speechRate\"+\n" +
	"\x03App\x12$\n" +
	"\x0ework_flow_name\x18\x01 \x01(\tR\fworkFlowName\"\x88\x01\n" +
	"\x04User\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x10\n" +
	"\x03did\x18\x02 \x01(\tR\x03did\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1f\n" +
	"\vsdk_version\x18\x04 \x01(\tR\n" +
	"sdkVersion\x12\x1f\n" +
	"\vapp_version\x18\x05 \x01(\tR\n" +
	"appVersion\"\xff\x02\n" +
	"\x05Audio\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x19\n" +
	"\burl_type\x18\x03 \x01(\tR\aurlType\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12\x14\n" +
	"\x05codec\x18\x05 \x01(\tR\x05codec\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x12\n" +
	"\x04rate\x18\a \x01(\x05R\x04rate\x12\x12\n" +
	"\x04bits\x18\b \x01(\x05R\x04bits\x12\x18\n" +
	"\achannel\x18\t \x01(\x05R\achannel\x12\x1d\n" +
	"\n" +
	"tos_bucket\x18\n" +
	" \x01(\tR\ttosBucket\x12$\n" +
	"\x0etos_access_key\x18\v \x01(\tR\ftosAccessKey\x12(\n" +
	"\x10audio_tos_object\x18\f \x01(\tR\x0eaudioTosObject\x12\x19\n" +
	"\brole_trn\x18\r \x01(\tR\aroleTrn\x12\x1f\n" +
	"\vbinary_data\x18\x0e \x01(\fR\n" +
	"binaryData\"o\n" +
	"\x0fAsrNotification\x12B\n" +
	"\x04code\x18\x01 \x01(\x0e2..data.speech.understanding.AsrNotificationCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa4\x11\n" +
	"\tReqParams\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x1f\n" +
	"\vconfig_name\x18\x02 \x01(\tR\n" +
	"configName\x12\"\n" +
	"\n" +
	"enable_vad\x18\x03 \x01(\bH\x00R\tenableVad\x88\x01\x01\x12$\n" +
	"\venable_punc\x18\x04 \x01(\bH\x01R\n" +
	"enablePunc\x88\x01\x01\x12\"\n" +
	"\n" +
	"enable_itn\x18\x05 \x01(\bH\x02R\tenableItn\x88\x01\x01\x12\"\n" +
	"\n" +
	"enable_ddc\x18\x06 \x01(\bH\x03R\tenableDdc\x88\x01\x01\x12,\n" +
	"\x0fenable_resample\x18\a \x01(\bH\x04R\x0eenableResample\x88\x01\x01\x12\"\n" +
	"\n" +
	"vad_signal\x18\b \x01(\bH\x05R\tvadSignal\x88\x01\x01\x12.\n" +
	"\x10enable_translate\x18\t \x01(\bH\x06R\x0fenableTranslate\x88\x01\x01\x12-\n" +
	"\x10disable_end_punc\x18\n" +
	" \x01(\bH\aR\x0edisableEndPunc\x88\x01\x01\x123\n" +
	"\x13enable_speaker_info\x18\v \x01(\bH\bR\x11enableSpeakerInfo\x88\x01\x01\x125\n" +
	"\x14enable_channel_split\x18\f \x01(\bH\tR\x12enableChannelSplit\x88\x01\x01\x12\x19\n" +
	"\bapp_lang\x18\r \x01(\tR\aappLang\x12\x18\n" +
	"\acountry\x18\x0e \x01(\tR\acountry\x12\x1d\n" +
	"\n" +
	"audio_type\x18\x0f \x01(\tR\taudioType\x12\"\n" +
	"\n" +
	"enable_lid\x18\x10 \x01(\bH\n" +
	"R\tenableLid\x88\x01\x01\x12(\n" +
	"\x10reco2act_num_spk\x18\x11 \x01(\x05R\x0ereco2actNumSpk\x12(\n" +
	"\x10reco2max_num_spk\x18\x12 \x01(\x05R\x0ereco2maxNumSpk\x12.\n" +
	"\x10enable_interrupt\x18\x13 \x01(\bH\vR\x0fenableInterrupt\x88\x01\x01\x12$\n" +
	"\vvad_segment\x18\x14 \x01(\bH\fR\n" +
	"vadSegment\x88\x01\x01\x12+\n" +
	"\x0fenable_ori_text\x18\x15 \x01(\bH\rR\renableOriText\x88\x01\x01\x12.\n" +
	"\x10enable_nonstream\x18\x16 \x01(\bH\x0eR\x0fenableNonstream\x88\x01\x01\x12,\n" +
	"\x0fshow_utterances\x18\x1f \x01(\bH\x0fR\x0eshowUtterances\x88\x01\x01\x12\"\n" +
	"\n" +
	"show_words\x18  \x01(\bH\x10R\tshowWords\x88\x01\x01\x12(\n" +
	"\rshow_duration\x18! \x01(\bH\x11R\fshowDuration\x88\x01\x01\x12(\n" +
	"\rshow_language\x18\" \x01(\bH\x12R\fshowLanguage\x88\x01\x01\x12$\n" +
	"\vshow_volume\x18# \x01(\bH\x13R\n" +
	"showVolume\x88\x01\x01\x12(\n" +
	"\rshow_volume_v\x18\xea\x02 \x01(\bH\x14R\vshowVolumeV\x88\x01\x01\x12-\n" +
	"\x10show_speech_rate\x18% \x01(\bH\x15R\x0eshowSpeechRate\x88\x01\x01\x12(\n" +
	"\rshow_prefetch\x18& \x01(\bH\x16R\fshowPrefetch\x88\x01\x01\x12\x1f\n" +
	"\vresult_type\x18' \x01(\tR\n" +
	"resultType\x12,\n" +
	"\x12start_silence_time\x18= \x01(\x05R\x10startSilenceTime\x12(\n" +
	"\x10end_silence_time\x18> \x01(\x05R\x0eendSilenceTime\x12(\n" +
	"\x10vad_silence_time\x18? \x01(\x05R\x0evadSilenceTime\x12(\n" +
	"\x10min_silence_time\x18@ \x01(\x05R\x0eminSilenceTime\x12\x19\n" +
	"\bvad_mode\x18A \x01(\tR\avadMode\x120\n" +
	"\x14vad_segment_duration\x18B \x01(\x05R\x12vadSegmentDuration\x12&\n" +
	"\x0fend_window_size\x18C \x01(\x05R\rendWindowSize\x12/\n" +
	"\x14force_to_speech_time\x18D \x01(\x05R\x11forceToSpeechTime\x129\n" +
	"\x06corpus\x18d \x01(\v2!.data.speech.understanding.CorpusR\x06corpus\x12N\n" +
	"\fnotification\x18e \x01(\v2*.data.speech.understanding.AsrNotificationR\fnotification\x124\n" +
	"\x16sensitive_words_filter\x18f \x01(\tR\x14sensitiveWordsFilterB\r\n" +
	"\v_enable_vadB\x0e\n" +
	"\f_enable_puncB\r\n" +
	"\v_enable_itnB\r\n" +
	"\v_enable_ddcB\x12\n" +
	"\x10_enable_resampleB\r\n" +
	"\v_vad_signalB\x13\n" +
	"\x11_enable_translateB\x13\n" +
	"\x11_disable_end_puncB\x16\n" +
	"\x14_enable_speaker_infoB\x17\n" +
	"\x15_enable_channel_splitB\r\n" +
	"\v_enable_lidB\x13\n" +
	"\x11_enable_interruptB\x0e\n" +
	"\f_vad_segmentB\x12\n" +
	"\x10_enable_ori_textB\x13\n" +
	"\x11_enable_nonstreamB\x12\n" +
	"\x10_show_utterancesB\r\n" +
	"\v_show_wordsB\x10\n" +
	"\x0e_show_durationB\x10\n" +
	"\x0e_show_languageB\x0e\n" +
	"\f_show_volumeB\x10\n" +
	"\x0e_show_volume_vB\x13\n" +
	"\x11_show_speech_rateB\x10\n" +
	"\x0e_show_prefetch\"\xea\a\n" +
	"\x06Corpus\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12*\n" +
	"\x11boosting_table_id\x18\x02 \x01(\tR\x0fboostingTableId\x12.\n" +
	"\x13boosting_table_name\x18\x03 \x01(\tR\x11boostingTableName\x12\x1f\n" +
	"\vboosting_id\x18\x04 \x01(\tR\n" +
	"boostingId\x12\x17\n" +
	"\annlm_id\x18\x05 \x01(\tR\x06nnlmId\x12(\n" +
	"\x10correct_table_id\x18\x06 \x01(\tR\x0ecorrectTableId\x12,\n" +
	"\x12correct_table_name\x18\a \x01(\tR\x10correctTableName\x12$\n" +
	"\x0epunc_hot_words\x18\b \x01(\tR\fpuncHotWords\x12$\n" +
	"\x0ehot_words_list\x18\t \x03(\tR\fhotWordsList\x12X\n" +
	"\rglossary_list\x18\n" +
	" \x03(\v23.data.speech.understanding.Corpus.GlossaryListEntryR\fglossaryList\x12#\n" +
	"\rcorrect_words\x18\v \x01(\tR\fcorrectWords\x123\n" +
	"\x16regex_correct_table_id\x18\f \x01(\tR\x13regexCorrectTableId\x127\n" +
	"\x18regex_correct_table_name\x18\r \x01(\tR\x15regexCorrectTableName\x12*\n" +
	"\x11glossary_table_id\x18\x0e \x01(\tR\x0fglossaryTableId\x12.\n" +
	"\x13glossary_table_name\x18\x0f \x01(\tR\x11glossaryTableName\x124\n" +
	"\x14show_match_hot_words\x18= \x01(\bH\x00R\x11showMatchHotWords\x88\x01\x01\x12;\n" +
	"\x18show_all_match_hot_words\x18> \x01(\bH\x01R\x14showAllMatchHotWords\x88\x01\x01\x12<\n" +
	"\x18show_effective_hot_words\x18? \x01(\bH\x02R\x15showEffectiveHotWords\x88\x01\x01\x1a?\n" +
	"\x11GlossaryListEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x17\n" +
	"\x15_show_match_hot_wordsB\x1b\n" +
	"\x19_show_all_match_hot_wordsB\x1b\n" +
	"\x19_show_effective_hot_words*\x8b\x03\n" +
	"\x04Code\x12\x15\n" +
	"\x11ERROR_UNSPECIFIED\x10\x00\x12\r\n" +
	"\aSUCCESS\x10\x88\xa4\x01\x12\x14\n" +
	"\x0fINVALID_REQUEST\x10\xdcV\x12\x16\n" +
	"\x11PERMISSION_DENIED\x10\xc0W\x12\x0e\n" +
	"\tLIMIT_QPS\x10\xa5X\x12\x10\n" +
	"\vLIMIT_COUNT\x10\xa6X\x12\x10\n" +
	"\vSERVER_BUSY\x10\xa7X\x12\x11\n" +
	"\vINTERRUPTED\x10\xb4\xa6\x01\x12\x11\n" +
	"\fERROR_PARAMS\x10\xecY\x12\x0f\n" +
	"\n" +
	"LONG_AUDIO\x10\xddV\x12\x11\n" +
	"\fLARGE_PACKET\x10\xdeV\x12\x13\n" +
	"\x0eINVALID_FORMAT\x10\xdfV\x12\x11\n" +
	"\fSILENT_AUDIO\x10\xe0V\x12\x10\n" +
	"\vEMPTY_AUDIO\x10\xe1V\x12\x19\n" +
	"\x13AUDIO_DOWNLOAD_FAIL\x10ũ\x01\x12\x15\n" +
	"\x0fTIMEOUT_WAITING\x10Х\x01\x12\x18\n" +
	"\x12TIMEOUT_PROCESSING\x10ѥ\x01\x12\x16\n" +
	"\x10ERROR_PROCESSING\x10\xec\xa4\x01\x12\x13\n" +
	"\rERROR_UNKNOWN\x10\xcc\xe9\x01*D\n" +
	"\x13AsrNotificationCode\x12\x1c\n" +
	"\x18NOTIFICATION_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\n" +
	"DISCONNECT\x10\xe8\ab\x06proto3"

var (
	file_products_understanding_base_au_base_proto_rawDescOnce sync.Once
	file_products_understanding_base_au_base_proto_rawDescData []byte
)

func file_products_understanding_base_au_base_proto_rawDescGZIP() []byte {
	file_products_understanding_base_au_base_proto_rawDescOnce.Do(func() {
		file_products_understanding_base_au_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_understanding_base_au_base_proto_rawDesc), len(file_products_understanding_base_au_base_proto_rawDesc)))
	})
	return file_products_understanding_base_au_base_proto_rawDescData
}

var file_products_understanding_base_au_base_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_products_understanding_base_au_base_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_products_understanding_base_au_base_proto_goTypes = []any{
	(Code)(0),                 // 0: data.speech.understanding.Code
	(AsrNotificationCode)(0),  // 1: data.speech.understanding.AsrNotificationCode
	(*Word)(nil),              // 2: data.speech.understanding.Word
	(*UtteranceAddition)(nil), // 3: data.speech.understanding.UtteranceAddition
	(*ResultAddition)(nil),    // 4: data.speech.understanding.ResultAddition
	(*Utterance)(nil),         // 5: data.speech.understanding.Utterance
	(*LanguageDetail)(nil),    // 6: data.speech.understanding.LanguageDetail
	(*Result)(nil),            // 7: data.speech.understanding.Result
	(*AudioInfo)(nil),         // 8: data.speech.understanding.AudioInfo
	(*App)(nil),               // 9: data.speech.understanding.App
	(*User)(nil),              // 10: data.speech.understanding.User
	(*Audio)(nil),             // 11: data.speech.understanding.Audio
	(*AsrNotification)(nil),   // 12: data.speech.understanding.AsrNotification
	(*ReqParams)(nil),         // 13: data.speech.understanding.ReqParams
	(*Corpus)(nil),            // 14: data.speech.understanding.Corpus
	nil,                       // 15: data.speech.understanding.Utterance.AdditionsEntry
	nil,                       // 16: data.speech.understanding.Result.LanguageDetailsEntry
	nil,                       // 17: data.speech.understanding.Result.AdditionsEntry
	nil,                       // 18: data.speech.understanding.Corpus.GlossaryListEntry
}
var file_products_understanding_base_au_base_proto_depIdxs = []int32{
	2,  // 0: data.speech.understanding.Utterance.words:type_name -> data.speech.understanding.Word
	15, // 1: data.speech.understanding.Utterance.additions:type_name -> data.speech.understanding.Utterance.AdditionsEntry
	5,  // 2: data.speech.understanding.Result.utterances:type_name -> data.speech.understanding.Utterance
	16, // 3: data.speech.understanding.Result.language_details:type_name -> data.speech.understanding.Result.LanguageDetailsEntry
	17, // 4: data.speech.understanding.Result.additions:type_name -> data.speech.understanding.Result.AdditionsEntry
	1,  // 5: data.speech.understanding.AsrNotification.code:type_name -> data.speech.understanding.AsrNotificationCode
	14, // 6: data.speech.understanding.ReqParams.corpus:type_name -> data.speech.understanding.Corpus
	12, // 7: data.speech.understanding.ReqParams.notification:type_name -> data.speech.understanding.AsrNotification
	18, // 8: data.speech.understanding.Corpus.glossary_list:type_name -> data.speech.understanding.Corpus.GlossaryListEntry
	6,  // 9: data.speech.understanding.Result.LanguageDetailsEntry.value:type_name -> data.speech.understanding.LanguageDetail
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_products_understanding_base_au_base_proto_init() }
func file_products_understanding_base_au_base_proto_init() {
	if File_products_understanding_base_au_base_proto != nil {
		return
	}
	file_products_understanding_base_au_base_proto_msgTypes[3].OneofWrappers = []any{}
	file_products_understanding_base_au_base_proto_msgTypes[5].OneofWrappers = []any{}
	file_products_understanding_base_au_base_proto_msgTypes[11].OneofWrappers = []any{}
	file_products_understanding_base_au_base_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_understanding_base_au_base_proto_rawDesc), len(file_products_understanding_base_au_base_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_products_understanding_base_au_base_proto_goTypes,
		DependencyIndexes: file_products_understanding_base_au_base_proto_depIdxs,
		EnumInfos:         file_products_understanding_base_au_base_proto_enumTypes,
		MessageInfos:      file_products_understanding_base_au_base_proto_msgTypes,
	}.Build()
	File_products_understanding_base_au_base_proto = out.File
	file_products_understanding_base_au_base_proto_goTypes = nil
	file_products_understanding_base_au_base_proto_depIdxs = nil
}
