// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: common/events.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	// 默认事件，适用于不使用事件的方案或不需要传递事件的情况，
	// 或者对于使用事件的方案，可以通过非0值来校验事件的合法性
	Type_None Type = 0
	// 1 ~ 49 为上行Connection事件
	Type_StartConnection  Type = 1
	Type_StartTask        Type = 1 // Alias of "StartConnection"
	Type_FinishConnection Type = 2
	Type_FinishTask       Type = 2 // Alias of "FinishConnection"
	// 50 ~ 99 为下行Connection事件
	// 成功建连
	Type_ConnectionStarted Type = 50
	Type_TaskStarted       Type = 50 // Alias of "ConnectionStarted"
	// 建连失败（可能是无法通过权限认证）
	Type_ConnectionFailed Type = 51
	Type_TaskFailed       Type = 51 // Alias of "ConnectionFailed"
	// 连接结束
	Type_ConnectionFinished Type = 52
	Type_TaskFinished       Type = 52 // Alias of "ConnectionFinished"
	// 100 ~ 149 为上行Session事件
	Type_StartSession  Type = 100
	Type_CancelSession Type = 101
	Type_FinishSession Type = 102
	// 150 ～ 199 为下行Session事件
	Type_SessionStarted  Type = 150
	Type_SessionCanceled Type = 151
	Type_SessionFinished Type = 152
	Type_SessionFailed   Type = 153
	// 用量事件
	Type_UsageResponse Type = 154
	Type_ChargeData    Type = 154 // Alias of "UsageResponse"
	// 200 ~ 249 为上行通用事件
	Type_TaskRequest  Type = 200
	Type_UpdateConfig Type = 201
	Type_ImageRequest Type = 202
	// 250 ~ 299 为下行通用事件
	Type_AudioMuted Type = 250
	// 300 ~ 349 为上行TTS事件
	Type_SayHello Type = 300
	// 350 ~ 399 为下行TTS事件
	Type_TTSSentenceStart     Type = 350
	Type_TTSSentenceEnd       Type = 351
	Type_TTSResponse          Type = 352
	Type_TTSEnded             Type = 359
	Type_PodcastRoundStart    Type = 360
	Type_PodcastRoundResponse Type = 361
	Type_PodcastRoundEnd      Type = 362
	// 450 ~ 499 为下行ASR事件
	Type_ASRInfo     Type = 450
	Type_ASRResponse Type = 451
	Type_ASREnded    Type = 459
	// 500 ~ 549 为上行对话事件
	// (Ground-Truth-Alignment) text for speech synthesis
	Type_ChatTTSText   Type = 500
	Type_ChatTextQuery Type = 501
	// 550 ~ 599 为下行对话事件
	Type_ChatResponse    Type = 550
	Type_ChimeInStart    Type = 551
	Type_ChimeInEnd      Type = 552
	Type_ChatEnded       Type = 559
	Type_ThinkStart      Type = 560
	Type_ThinkResponse   Type = 561
	Type_ThinkEnd        Type = 562
	Type_ToolOutput      Type = 563
	Type_FCResponseStart Type = 564
	Type_FCResponse      Type = 565
	Type_FCResponseEnd   Type = 566
	// 650 ~ 699 为下行对话事件
	// Events for source (original) language subtitle.
	Type_SourceSubtitleStart    Type = 650
	Type_SourceSubtitleResponse Type = 651
	Type_SourceSubtitleEnd      Type = 652
	// Events for target (translation) language subtitle.
	Type_TranslationSubtitleStart    Type = 653
	Type_TranslationSubtitleResponse Type = 654
	Type_TranslationSubtitleEnd      Type = 655
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "None",
		1: "StartConnection",
		// Duplicate value: 1: "StartTask",
		2: "FinishConnection",
		// Duplicate value: 2: "FinishTask",
		50: "ConnectionStarted",
		// Duplicate value: 50: "TaskStarted",
		51: "ConnectionFailed",
		// Duplicate value: 51: "TaskFailed",
		52: "ConnectionFinished",
		// Duplicate value: 52: "TaskFinished",
		100: "StartSession",
		101: "CancelSession",
		102: "FinishSession",
		150: "SessionStarted",
		151: "SessionCanceled",
		152: "SessionFinished",
		153: "SessionFailed",
		154: "UsageResponse",
		// Duplicate value: 154: "ChargeData",
		200: "TaskRequest",
		201: "UpdateConfig",
		202: "ImageRequest",
		250: "AudioMuted",
		300: "SayHello",
		350: "TTSSentenceStart",
		351: "TTSSentenceEnd",
		352: "TTSResponse",
		359: "TTSEnded",
		360: "PodcastRoundStart",
		361: "PodcastRoundResponse",
		362: "PodcastRoundEnd",
		450: "ASRInfo",
		451: "ASRResponse",
		459: "ASREnded",
		500: "ChatTTSText",
		501: "ChatTextQuery",
		550: "ChatResponse",
		551: "ChimeInStart",
		552: "ChimeInEnd",
		559: "ChatEnded",
		560: "ThinkStart",
		561: "ThinkResponse",
		562: "ThinkEnd",
		563: "ToolOutput",
		564: "FCResponseStart",
		565: "FCResponse",
		566: "FCResponseEnd",
		650: "SourceSubtitleStart",
		651: "SourceSubtitleResponse",
		652: "SourceSubtitleEnd",
		653: "TranslationSubtitleStart",
		654: "TranslationSubtitleResponse",
		655: "TranslationSubtitleEnd",
	}
	Type_value = map[string]int32{
		"None":                        0,
		"StartConnection":             1,
		"StartTask":                   1,
		"FinishConnection":            2,
		"FinishTask":                  2,
		"ConnectionStarted":           50,
		"TaskStarted":                 50,
		"ConnectionFailed":            51,
		"TaskFailed":                  51,
		"ConnectionFinished":          52,
		"TaskFinished":                52,
		"StartSession":                100,
		"CancelSession":               101,
		"FinishSession":               102,
		"SessionStarted":              150,
		"SessionCanceled":             151,
		"SessionFinished":             152,
		"SessionFailed":               153,
		"UsageResponse":               154,
		"ChargeData":                  154,
		"TaskRequest":                 200,
		"UpdateConfig":                201,
		"ImageRequest":                202,
		"AudioMuted":                  250,
		"SayHello":                    300,
		"TTSSentenceStart":            350,
		"TTSSentenceEnd":              351,
		"TTSResponse":                 352,
		"TTSEnded":                    359,
		"PodcastRoundStart":           360,
		"PodcastRoundResponse":        361,
		"PodcastRoundEnd":             362,
		"ASRInfo":                     450,
		"ASRResponse":                 451,
		"ASREnded":                    459,
		"ChatTTSText":                 500,
		"ChatTextQuery":               501,
		"ChatResponse":                550,
		"ChimeInStart":                551,
		"ChimeInEnd":                  552,
		"ChatEnded":                   559,
		"ThinkStart":                  560,
		"ThinkResponse":               561,
		"ThinkEnd":                    562,
		"ToolOutput":                  563,
		"FCResponseStart":             564,
		"FCResponse":                  565,
		"FCResponseEnd":               566,
		"SourceSubtitleStart":         650,
		"SourceSubtitleResponse":      651,
		"SourceSubtitleEnd":           652,
		"TranslationSubtitleStart":    653,
		"TranslationSubtitleResponse": 654,
		"TranslationSubtitleEnd":      655,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_common_events_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_common_events_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_common_events_proto_rawDescGZIP(), []int{0}
}

var File_common_events_proto protoreflect.FileDescriptor

const file_common_events_proto_rawDesc = "" +
	"\n" +
	"\x13common/events.proto\x12\x11data.speech.event*\xbf\b\n" +
	"\x04Type\x12\b\n" +
	"\x04None\x10\x00\x12\x13\n" +
	"\x0fStartConnection\x10\x01\x12\r\n" +
	"\tStartTask\x10\x01\x12\x14\n" +
	"\x10FinishConnection\x10\x02\x12\x0e\n" +
	"\n" +
	"FinishTask\x10\x02\x12\x15\n" +
	"\x11ConnectionStarted\x102\x12\x0f\n" +
	"\vTaskStarted\x102\x12\x14\n" +
	"\x10ConnectionFailed\x103\x12\x0e\n" +
	"\n" +
	"TaskFailed\x103\x12\x16\n" +
	"\x12ConnectionFinished\x104\x12\x10\n" +
	"\fTaskFinished\x104\x12\x10\n" +
	"\fStartSession\x10d\x12\x11\n" +
	"\rCancelSession\x10e\x12\x11\n" +
	"\rFinishSession\x10f\x12\x13\n" +
	"\x0eSessionStarted\x10\x96\x01\x12\x14\n" +
	"\x0fSessionCanceled\x10\x97\x01\x12\x14\n" +
	"\x0fSessionFinished\x10\x98\x01\x12\x12\n" +
	"\rSessionFailed\x10\x99\x01\x12\x12\n" +
	"\rUsageResponse\x10\x9a\x01\x12\x0f\n" +
	"\n" +
	"ChargeData\x10\x9a\x01\x12\x10\n" +
	"\vTaskRequest\x10\xc8\x01\x12\x11\n" +
	"\fUpdateConfig\x10\xc9\x01\x12\x11\n" +
	"\fImageRequest\x10\xca\x01\x12\x0f\n" +
	"\n" +
	"AudioMuted\x10\xfa\x01\x12\r\n" +
	"\bSayHello\x10\xac\x02\x12\x15\n" +
	"\x10TTSSentenceStart\x10\xde\x02\x12\x13\n" +
	"\x0eTTSSentenceEnd\x10\xdf\x02\x12\x10\n" +
	"\vTTSResponse\x10\xe0\x02\x12\r\n" +
	"\bTTSEnded\x10\xe7\x02\x12\x16\n" +
	"\x11PodcastRoundStart\x10\xe8\x02\x12\x19\n" +
	"\x14PodcastRoundResponse\x10\xe9\x02\x12\x14\n" +
	"\x0fPodcastRoundEnd\x10\xea\x02\x12\f\n" +
	"\aASRInfo\x10\xc2\x03\x12\x10\n" +
	"\vASRResponse\x10\xc3\x03\x12\r\n" +
	"\bASREnded\x10\xcb\x03\x12\x10\n" +
	"\vChatTTSText\x10\xf4\x03\x12\x12\n" +
	"\rChatTextQuery\x10\xf5\x03\x12\x11\n" +
	"\fChatResponse\x10\xa6\x04\x12\x11\n" +
	"\fChimeInStart\x10\xa7\x04\x12\x0f\n" +
	"\n" +
	"ChimeInEnd\x10\xa8\x04\x12\x0e\n" +
	"\tChatEnded\x10\xaf\x04\x12\x0f\n" +
	"\n" +
	"ThinkStart\x10\xb0\x04\x12\x12\n" +
	"\rThinkResponse\x10\xb1\x04\x12\r\n" +
	"\bThinkEnd\x10\xb2\x04\x12\x0f\n" +
	"\n" +
	"ToolOutput\x10\xb3\x04\x12\x14\n" +
	"\x0fFCResponseStart\x10\xb4\x04\x12\x0f\n" +
	"\n" +
	"FCResponse\x10\xb5\x04\x12\x12\n" +
	"\rFCResponseEnd\x10\xb6\x04\x12\x18\n" +
	"\x13SourceSubtitleStart\x10\x8a\x05\x12\x1b\n" +
	"\x16SourceSubtitleResponse\x10\x8b\x05\x12\x16\n" +
	"\x11SourceSubtitleEnd\x10\x8c\x05\x12\x1d\n" +
	"\x18TranslationSubtitleStart\x10\x8d\x05\x12 \n" +
	"\x1bTranslationSubtitleResponse\x10\x8e\x05\x12\x1b\n" +
	"\x16TranslationSubtitleEnd\x10\x8f\x05\x1a\x02\x10\x01b\x06proto3"

var (
	file_common_events_proto_rawDescOnce sync.Once
	file_common_events_proto_rawDescData []byte
)

func file_common_events_proto_rawDescGZIP() []byte {
	file_common_events_proto_rawDescOnce.Do(func() {
		file_common_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_events_proto_rawDesc), len(file_common_events_proto_rawDesc)))
	})
	return file_common_events_proto_rawDescData
}

var file_common_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_events_proto_goTypes = []any{
	(Type)(0), // 0: data.speech.event.Type
}
var file_common_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_events_proto_init() }
func file_common_events_proto_init() {
	if File_common_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_events_proto_rawDesc), len(file_common_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_events_proto_goTypes,
		DependencyIndexes: file_common_events_proto_depIdxs,
		EnumInfos:         file_common_events_proto_enumTypes,
	}.Build()
	File_common_events_proto = out.File
	file_common_events_proto_goTypes = nil
	file_common_events_proto_depIdxs = nil
}
