// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: products/understanding/ast/ast_service.proto

package ast

import (
	event "code.byted.org/data-speech/wsclientsdk/protogen/common/event"
	rpcmeta "code.byted.org/data-speech/wsclientsdk/protogen/common/rpcmeta"
	base "code.byted.org/data-speech/wsclientsdk/protogen/products/understanding/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqParams struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Mode           string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`                                           // 可能是s2t , s2s 选一个, 控制是否需要语音
	SourceLanguage string                 `protobuf:"bytes,2,opt,name=source_language,json=sourceLanguage,proto3" json:"source_language,omitempty"` // 源语言
	TargetLanguage string                 `protobuf:"bytes,3,opt,name=target_language,json=targetLanguage,proto3" json:"target_language,omitempty"` // 目标语言
	SpeakerId      string                 `protobuf:"bytes,4,opt,name=speaker_id,json=speakerId,proto3" json:"speaker_id,omitempty"`
	SpeechRate     int32                  `protobuf:"varint,5,opt,name=speech_rate,json=speechRate,proto3" json:"speech_rate,omitempty"` // 外接音色语速，默认0
	Corpus         *base.Corpus           `protobuf:"bytes,100,opt,name=corpus,proto3" json:"corpus,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReqParams) Reset() {
	*x = ReqParams{}
	mi := &file_products_understanding_ast_ast_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqParams) ProtoMessage() {}

func (x *ReqParams) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_ast_ast_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqParams.ProtoReflect.Descriptor instead.
func (*ReqParams) Descriptor() ([]byte, []int) {
	return file_products_understanding_ast_ast_service_proto_rawDescGZIP(), []int{0}
}

func (x *ReqParams) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ReqParams) GetSourceLanguage() string {
	if x != nil {
		return x.SourceLanguage
	}
	return ""
}

func (x *ReqParams) GetTargetLanguage() string {
	if x != nil {
		return x.TargetLanguage
	}
	return ""
}

func (x *ReqParams) GetSpeakerId() string {
	if x != nil {
		return x.SpeakerId
	}
	return ""
}

func (x *ReqParams) GetSpeechRate() int32 {
	if x != nil {
		return x.SpeechRate
	}
	return 0
}

func (x *ReqParams) GetCorpus() *base.Corpus {
	if x != nil {
		return x.Corpus
	}
	return nil
}

type TranslateRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	RequestMeta *rpcmeta.RequestMeta   `protobuf:"bytes,1,opt,name=request_meta,json=requestMeta,proto3,oneof" json:"request_meta,omitempty"`
	Event       event.Type             `protobuf:"varint,2,opt,name=event,proto3,enum=data.speech.event.Type" json:"event,omitempty"`
	User        *base.User             `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	// bytes data = 2;               // request binary data
	SourceAudio *base.Audio `protobuf:"bytes,4,opt,name=source_audio,json=sourceAudio,proto3" json:"source_audio,omitempty"` // 源音频信息
	// 目标音频信息，只需要传format（pcm/ogg）、rate、bits、channel这些
	TargetAudio   *base.Audio `protobuf:"bytes,5,opt,name=target_audio,json=targetAudio,proto3" json:"target_audio,omitempty"`
	Request       *ReqParams  `protobuf:"bytes,6,opt,name=request,proto3" json:"request,omitempty"`        // 请求参数
	Denoise       *bool       `protobuf:"varint,7,opt,name=denoise,proto3,oneof" json:"denoise,omitempty"` // 是否开启降噪
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranslateRequest) Reset() {
	*x = TranslateRequest{}
	mi := &file_products_understanding_ast_ast_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateRequest) ProtoMessage() {}

func (x *TranslateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_ast_ast_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateRequest.ProtoReflect.Descriptor instead.
func (*TranslateRequest) Descriptor() ([]byte, []int) {
	return file_products_understanding_ast_ast_service_proto_rawDescGZIP(), []int{1}
}

func (x *TranslateRequest) GetRequestMeta() *rpcmeta.RequestMeta {
	if x != nil {
		return x.RequestMeta
	}
	return nil
}

func (x *TranslateRequest) GetEvent() event.Type {
	if x != nil {
		return x.Event
	}
	return event.Type(0)
}

func (x *TranslateRequest) GetUser() *base.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TranslateRequest) GetSourceAudio() *base.Audio {
	if x != nil {
		return x.SourceAudio
	}
	return nil
}

func (x *TranslateRequest) GetTargetAudio() *base.Audio {
	if x != nil {
		return x.TargetAudio
	}
	return nil
}

func (x *TranslateRequest) GetRequest() *ReqParams {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TranslateRequest) GetDenoise() bool {
	if x != nil && x.Denoise != nil {
		return *x.Denoise
	}
	return false
}

type TranslateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResponseMeta    *rpcmeta.ResponseMeta  `protobuf:"bytes,1,opt,name=response_meta,json=responseMeta,proto3,oneof" json:"response_meta,omitempty"`
	Event           event.Type             `protobuf:"varint,2,opt,name=event,proto3,enum=data.speech.event.Type" json:"event,omitempty"`
	Data            []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // response binary data
	Text            string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"` // 原文或者译文
	StartTime       int32                  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         int32                  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SpkChg          bool                   `protobuf:"varint,7,opt,name=spk_chg,json=spkChg,proto3" json:"spk_chg,omitempty"`
	MutedDurationMs int32                  `protobuf:"varint,8,opt,name=muted_duration_ms,json=mutedDurationMs,proto3" json:"muted_duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TranslateResponse) Reset() {
	*x = TranslateResponse{}
	mi := &file_products_understanding_ast_ast_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranslateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResponse) ProtoMessage() {}

func (x *TranslateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_understanding_ast_ast_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateResponse.ProtoReflect.Descriptor instead.
func (*TranslateResponse) Descriptor() ([]byte, []int) {
	return file_products_understanding_ast_ast_service_proto_rawDescGZIP(), []int{2}
}

func (x *TranslateResponse) GetResponseMeta() *rpcmeta.ResponseMeta {
	if x != nil {
		return x.ResponseMeta
	}
	return nil
}

func (x *TranslateResponse) GetEvent() event.Type {
	if x != nil {
		return x.Event
	}
	return event.Type(0)
}

func (x *TranslateResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TranslateResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranslateResponse) GetStartTime() int32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TranslateResponse) GetEndTime() int32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TranslateResponse) GetSpkChg() bool {
	if x != nil {
		return x.SpkChg
	}
	return false
}

func (x *TranslateResponse) GetMutedDurationMs() int32 {
	if x != nil {
		return x.MutedDurationMs
	}
	return 0
}

var File_products_understanding_ast_ast_service_proto protoreflect.FileDescriptor

const file_products_understanding_ast_ast_service_proto_rawDesc = "" +
	"\n" +
	",products/understanding/ast/ast_service.proto\x12\x0fdata.speech.ast\x1a\x13common/events.proto\x1a\x14common/rpcmeta.proto\x1a)products/understanding/base/au_base.proto\"\xec\x01\n" +
	"\tReqParams\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12'\n" +
	"\x0fsource_language\x18\x02 \x01(\tR\x0esourceLanguage\x12'\n" +
	"\x0ftarget_language\x18\x03 \x01(\tR\x0etargetLanguage\x12\x1d\n" +
	"\n" +
	"speaker_id\x18\x04 \x01(\tR\tspeakerId\x12\x1f\n" +
	"\vspeech_rate\x18\x05 \x01(\x05R\n" +
	"speechRate\x129\n" +
	"\x06corpus\x18d \x01(\v2!.data.speech.understanding.CorpusR\x06corpus\"\xbb\x03\n" +
	"\x10TranslateRequest\x12G\n" +
	"\frequest_meta\x18\x01 \x01(\v2\x1f.data.speech.common.RequestMetaH\x00R\vrequestMeta\x88\x01\x01\x12-\n" +
	"\x05event\x18\x02 \x01(\x0e2\x17.data.speech.event.TypeR\x05event\x123\n" +
	"\x04user\x18\x03 \x01(\v2\x1f.data.speech.understanding.UserR\x04user\x12C\n" +
	"\fsource_audio\x18\x04 \x01(\v2 .data.speech.understanding.AudioR\vsourceAudio\x12C\n" +
	"\ftarget_audio\x18\x05 \x01(\v2 .data.speech.understanding.AudioR\vtargetAudio\x124\n" +
	"\arequest\x18\x06 \x01(\v2\x1a.data.speech.ast.ReqParamsR\arequest\x12\x1d\n" +
	"\adenoise\x18\a \x01(\bH\x01R\adenoise\x88\x01\x01B\x0f\n" +
	"\r_request_metaB\n" +
	"\n" +
	"\b_denoise\"\xc7\x02\n" +
	"\x11TranslateResponse\x12J\n" +
	"\rresponse_meta\x18\x01 \x01(\v2 .data.speech.common.ResponseMetaH\x00R\fresponseMeta\x88\x01\x01\x12-\n" +
	"\x05event\x18\x02 \x01(\x0e2\x17.data.speech.event.TypeR\x05event\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\x05R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\x05R\aendTime\x12\x17\n" +
	"\aspk_chg\x18\a \x01(\bR\x06spkChg\x12*\n" +
	"\x11muted_duration_ms\x18\b \x01(\x05R\x0fmutedDurationMsB\x10\n" +
	"\x0e_response_meta2d\n" +
	"\n" +
	"ASTService\x12V\n" +
	"\tTranslate\x12!.data.speech.ast.TranslateRequest\x1a\".data.speech.ast.TranslateResponse(\x010\x01b\x06proto3"

var (
	file_products_understanding_ast_ast_service_proto_rawDescOnce sync.Once
	file_products_understanding_ast_ast_service_proto_rawDescData []byte
)

func file_products_understanding_ast_ast_service_proto_rawDescGZIP() []byte {
	file_products_understanding_ast_ast_service_proto_rawDescOnce.Do(func() {
		file_products_understanding_ast_ast_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_understanding_ast_ast_service_proto_rawDesc), len(file_products_understanding_ast_ast_service_proto_rawDesc)))
	})
	return file_products_understanding_ast_ast_service_proto_rawDescData
}

var file_products_understanding_ast_ast_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_products_understanding_ast_ast_service_proto_goTypes = []any{
	(*ReqParams)(nil),            // 0: data.speech.ast.ReqParams
	(*TranslateRequest)(nil),     // 1: data.speech.ast.TranslateRequest
	(*TranslateResponse)(nil),    // 2: data.speech.ast.TranslateResponse
	(*base.Corpus)(nil),          // 3: data.speech.understanding.Corpus
	(*rpcmeta.RequestMeta)(nil),  // 4: data.speech.common.RequestMeta
	(event.Type)(0),              // 5: data.speech.event.Type
	(*base.User)(nil),            // 6: data.speech.understanding.User
	(*base.Audio)(nil),           // 7: data.speech.understanding.Audio
	(*rpcmeta.ResponseMeta)(nil), // 8: data.speech.common.ResponseMeta
}
var file_products_understanding_ast_ast_service_proto_depIdxs = []int32{
	3,  // 0: data.speech.ast.ReqParams.corpus:type_name -> data.speech.understanding.Corpus
	4,  // 1: data.speech.ast.TranslateRequest.request_meta:type_name -> data.speech.common.RequestMeta
	5,  // 2: data.speech.ast.TranslateRequest.event:type_name -> data.speech.event.Type
	6,  // 3: data.speech.ast.TranslateRequest.user:type_name -> data.speech.understanding.User
	7,  // 4: data.speech.ast.TranslateRequest.source_audio:type_name -> data.speech.understanding.Audio
	7,  // 5: data.speech.ast.TranslateRequest.target_audio:type_name -> data.speech.understanding.Audio
	0,  // 6: data.speech.ast.TranslateRequest.request:type_name -> data.speech.ast.ReqParams
	8,  // 7: data.speech.ast.TranslateResponse.response_meta:type_name -> data.speech.common.ResponseMeta
	5,  // 8: data.speech.ast.TranslateResponse.event:type_name -> data.speech.event.Type
	1,  // 9: data.speech.ast.ASTService.Translate:input_type -> data.speech.ast.TranslateRequest
	2,  // 10: data.speech.ast.ASTService.Translate:output_type -> data.speech.ast.TranslateResponse
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_products_understanding_ast_ast_service_proto_init() }
func file_products_understanding_ast_ast_service_proto_init() {
	if File_products_understanding_ast_ast_service_proto != nil {
		return
	}
	file_products_understanding_ast_ast_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_products_understanding_ast_ast_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_understanding_ast_ast_service_proto_rawDesc), len(file_products_understanding_ast_ast_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_understanding_ast_ast_service_proto_goTypes,
		DependencyIndexes: file_products_understanding_ast_ast_service_proto_depIdxs,
		MessageInfos:      file_products_understanding_ast_ast_service_proto_msgTypes,
	}.Build()
	File_products_understanding_ast_ast_service_proto = out.File
	file_products_understanding_ast_ast_service_proto_goTypes = nil
	file_products_understanding_ast_ast_service_proto_depIdxs = nil
}
